# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    allow:
      - dependency-type: "development"
    commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "devcontainers"
    commit-message:
      include: "scope"
      prefix: "devcontainers"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
